### ISSUE TITLE
how to downsample webvid2m videos to 10% of the original FPS

### ISSUE THREAD

**Issue by 1024er** [salesforce/ALPRO#1]
As you mentioned in pretraining data preparation "we downsample webvid2m videos to 10% of the original FPS to speed-up video loading",  can you elaborate on how to achieve this?

Thank you

**Comment by 1024er** [comment]
As you mentioned in the paper: "We pre-train ALPRO for 100k iterations, roughly equivalent to 10 epochs, using a batch size of 256 on 16 NVIDIA A100 GPUs."

How many hours does it take to complete pre-training?

Thank you

**Comment by dxli94** [comment]
> As you mentioned in pretraining data preparation "we downsample webvid2m videos to 10% of the original FPS to speed-up video loading", can you elaborate on how to achieve this?
> 
> Thank you

We use FFMPEG to downsample videos, please find the section of "setpts" in their official wiki (https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video).

**Comment by dxli94** [comment]
> As you mentioned in the paper: "We pre-train ALPRO for 100k iterations, roughly equivalent to 10 epochs, using a batch size of 256 on 16 NVIDIA A100 GPUs."
> 
> How many hours does it take to complete pre-training?
> 
> Thank you

Training baseline MLM + VTM or prompter costs 1 - 1.5 days. Training full ALPRO costs additional 1-1.5 days, plus the prompter which amounts to 2-3 days in total.

**Comment by dxli94** [comment]
I will close the issue for now.

Please reopen if the question remains.
