### ISSUE TITLE
Using multiple GPUs vs single GPU

### ISSUE THREAD

**Issue by avinashsai** [salesforce/ALPRO#12]
Hi,

Congratulations on the amazing work. Will there be any difference in performance if I use just a single GPU and what are the changes to be made in eg: msvd_qa.json?

Thank you.

**Comment by dxli94** [comment]
Using single gpu ends up with smaller number of samples in a batch. So you might need to increase the "gradient_accumulation_steps" to simulate multiple GPUs case. See how it works [here](https://kozodoi.me/python/deep%20learning/pytorch/tutorial/2021/02/19/gradient-accumulation.html). Conceptually this should give you same results after a longer training time, though non-determinism might cause minor performance difference, too.
