### ISSUE TITLE
How to initialize the model with ALBEF when finetuning?

### ISSUE THREAD

**Issue by cdqncn** [salesforce/ALPRO#5]

**Comment by cdqncn** [comment]
I noticed that your codes have a comment "# NOTE strict is False if loaded from ALBEF ckpt", when I did finetune on downstream tasks, I want to try to use the released ALBEF.pth to initialize the model, but some error appeared.
Could you help me? Thanks!

**Comment by dxli94** [comment]
The comment is deprecated. 

ALPRO has a different model architecture from ALBEF. Reusing some weights from ALBEF for initialization is possible but currently not supported by the codebase.

If desired, you may manually load weights from ALBEF model state_dict().

Thanks.
