### ISSUE TITLE
MSR-VTT dataset split

### ISSUE THREAD

**Issue by chaochen99** [salesforce/ALPRO#6]
Hi, 
Thanks for sharing the code!

I saw "use 7k videos for training and report results on the 1k test split" in your paper. When I downloaded the MSR-VTT dataset, there are only 7K train sets and 3K test sets, but no val dataset. Could you share the code for dividing the dataset to avoid discrepancies in results?

Looking forward to your reply.

**Comment by dxli94** [comment]
Once you downloaded and unzipped the data.zip, you will be able to find the annotations by split in e.g. msrvtt_ret directory. This partition follows the common partition protocol in previous works. Thanks.
