### ISSUE TITLE
MSR-VTT Zero-shot

### ISSUE THREAD

**Issue by chaochen99** [salesforce/ALPRO#7]
Hi ,

I saw "We pre-train ALPRO for 100k iterations, roughly equivalent to 10 epochs" in your paper. So there will be ten checkpoints, which one is the zero-shot checkpoint for testing MSRVTT, and how to choose?

Looking forward to your reply, thanks!

**Comment by dxli94** [comment]
We choose the last checkpoint after pre-training. No further strategy is adopted.
